name: Mirror to Gitea

on: [push, delete] # Spustí sa pri každom pushi alebo zmazaní vetvy

jobs:
  gitea-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Mirror to Gitea
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.GITEA_URL }}
          target_username: "xrucekk00"
          target_password: ${{ secrets.GITEA_TOKEN }}
