name: Mirror to Gitea

on: [push, delete]

jobs:
  gitea-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirror to Gitea
        run: |
          # Vyčistíme URL od prípadného https:// na začiatku
          CLEAN_URL=$(echo "${{ secrets.GITEA_URL }}" | sed 's|https://||')
          
          # Poskladáme finálnu URL s autentifikáciou
          REMOTE_URL="https://${{ github.actor }}:${{ secrets.GITEA_TOKEN }}@$CLEAN_URL"
          
          # Pushneme mirror
          git push --mirror $REMOTE_URL