name: Mirror to Gitea

on: [push, delete]

jobs:
  gitea-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirror to Gitea
        run: |
          # Vytvoríme URL so zapuzdreným tokenom pre autentifikáciu
          # GITEA_URL musí byť v tvare: https://gitea.fit.vut.cz/xlogin00/ipp-projekt.git
          REMOTE_URL="https://${{ github.actor }}:${{ secrets.GITEA_TOKEN }}@${{ secrets.GITEA_URL | replace('https://', '') }}"
          git push --mirror $REMOTE_URL